builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      #- darwin
      - windows
      - freebsd
    goarch:
      - amd64
      #- arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.version={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"
    overrides:
      - goos: linux
        goarch: arm
        env:
          - CC=arm-linux-gnueabi-gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - Readme.md
