builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: app
    ldflags: "-s -w -X main.version={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"
    
checksum:
  name_template: "{{ .ProjectName }}_darwin_checksums.txt"
  
signs:
  - artifacts: checksum
  - stdin: '{{ .Env.GPG_PASSWORD }}'  
archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    rlcp: true
    files:
      - LICENSE.md
      - Readme.md
