builds:
  - env:
      - CGO_ENABLED=1
    id: linux_windows  
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: app
    ldflags: "-s -w -X main.version={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"
    overrides:
      - goos: linux
        goarch: arm
        goarm: 6
        env:
          - CC=arm-linux-gnueabi-gcc 
      - goos: windows
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-w64-mingw32-gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc

checksum:
  name_template: "{{ .ProjectName }}_linux_windows_checksums.txt"
  
signs:
  - artifacts: checksum
  - stdin: '{{ .Env.GPG_PASSWORD }}'
            
archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    id: linux_windows
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - Readme.md
