name: build

on:
  push:
    branches:
    tags:
    paths:
      - ".github/workflows/ci-build.yml"
      - "app/**"
      - "frontend/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"

  pull_request:
    paths:
      - ".github/workflows/ci-build.yml"
      - "app/**"
      - "frontend/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.15.1 ]
    steps:
      - name: check for tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo ${GITHUB_REF} | cut -d'/' -f3
             
      - name: disable and stop mono-xsp4.service
        run: |
          sudo systemctl stop mono-xsp4.service || true
          sudo systemctl disable mono-xsp4.service || true

      - name: set up go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
        id: go

      - name: checkout
        uses: actions/checkout@v2
           
