name: release-binary

on:
  push:
    branches: [ master ]
    tags:
      #- "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-linux-windows-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        go-version: 1.19
        check-latest: true
        cache: true

      # build frontend stage
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: "frontend/yarn.lock"

      - name: Install project dependencies
        working-directory: ./frontend
        run: |
          yarn --prefer-offline

      - name: Build frontend
        working-directory: ./frontend
        run: |
          yarn build
          cp -r build/* ../app/web

      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get -y install gcc-aarch64-linux-gnu
      - name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --config .goreleaser.yml
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
